apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: game-2048
---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: game-2048
